"""Version-controlled defaults for the isolated regime-intraday service."""

from __future__ import annotations

import os


INTRADAY_DEFAULTS = {
    "DATA_FEED": "iex",
    "DATA_ADJUSTMENT": "raw",
    "REGIME_INTRADAY_LEDGER_PATH": "/var/data/regime_intraday_ledger.json",
    "REGIME_INTRADAY_TRADE_SYMBOLS": "SPY",
    "REGIME_INTRADAY_MOMENTUM_ENABLED": "false",
    "REGIME_INTRADAY_MEAN_REVERSION_ENABLED": "true",
    "REGIME_INTRADAY_OPENING_RANGE_MINUTES": "30",
    "REGIME_INTRADAY_MIN_BARS": "40",
    "REGIME_INTRADAY_MOMENTUM_VOLUME_RATIO": "1.20",
    "REGIME_INTRADAY_BREAK_BUFFER_PCT": "0.0003",
    "REGIME_INTRADAY_MAX_VWAP_EXTENSION_PCT": "0.008",
    "REGIME_INTRADAY_TREND_EFFICIENCY_MIN": "0.34",
    "REGIME_INTRADAY_RANGE_EFFICIENCY_MAX": "0.24",
    "REGIME_INTRADAY_MR_MIN_VWAP_ATR": "1.0",
    "REGIME_INTRADAY_MR_MAX_VWAP_ATR": "2.75",
    "REGIME_INTRADAY_STOP_ATR": "0.75",
    "REGIME_INTRADAY_TARGET_R": "2.0",
    "REGIME_INTRADAY_OPTION_MIN_DTE": "7",
    "REGIME_INTRADAY_OPTION_MAX_DTE": "21",
    "REGIME_INTRADAY_OPTION_DELTA_LOW": "0.55",
    "REGIME_INTRADAY_OPTION_DELTA_HIGH": "0.70",
    "REGIME_INTRADAY_OPTION_MAX_SPREAD_PCT": "0.08",
    "REGIME_INTRADAY_OPTION_CHAIN_ENABLED": "true",
    "REGIME_INTRADAY_OPTION_FEED": "indicative",
    "REGIME_INTRADAY_OPTION_CHAIN_TIMEOUT_SEC": "20",
    "REGIME_INTRADAY_MAX_TRADE_LOSS_DOLLARS": "100",
    "REGIME_INTRADAY_MAX_DAILY_LOSS_DOLLARS": "200",
    "REGIME_INTRADAY_MAX_DAILY_LOSS_R": "2.0",
    "REGIME_INTRADAY_MAX_OPEN_POSITIONS": "1",
    "REGIME_INTRADAY_MAX_TRADES_PER_DAY": "2",
    "REGIME_INTRADAY_MAX_CONSECUTIVE_LOSSES": "2",
    "REGIME_INTRADAY_MAX_SCAN_AGE_SEC": "600",
    "REGIME_INTRADAY_MIN_SHADOW_CLOSED_FOR_LIVE": "10",
    "REGIME_INTRADAY_LATEST_ENTRY_TIME_NY": "15:30",
    "REGIME_INTRADAY_FORCED_EXIT_TIME_NY": "15:45",
    "REGIME_INTRADAY_STALE_ENTRY_SEC": "120",
    "REGIME_INTRADAY_PAPER_AUTO_SUBMIT": "true",
    "REGIME_INTRADAY_PAPER_AUTO_EXIT": "true",
    "REGIME_INTRADAY_PAPER_AUTO_CANCEL_STALE": "true",
    "REGIME_INTRADAY_TAKE_PROFIT_FRACTION": "0.50",
    "REGIME_INTRADAY_STOP_LOSS_FRACTION": "0.50",
    "REGIME_INTRADAY_ALERT_EMAIL_ENABLED": "true",
    "REGIME_INTRADAY_ALERT_EMAIL_FROM": "Trading System <onboarding@resend.dev>",
    "REGIME_INTRADAY_CANDIDATE_TTL_SEC": "600",
    "REGIME_INTRADAY_VALIDATION_DAYS": "180",
    "ONLY_MARKET_HOURS": "true",
}


def apply_intraday_defaults() -> None:
    for key, value in INTRADAY_DEFAULTS.items():
        os.environ.setdefault(key, value)
